<a href="https://colab.research.google.com/github/fesaez/jupyter/blob/master/tratamentonulo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
dados = {
    'id_cliente': [101, 102, 103, 104],
    'saldo': [500, 6500, 7000, 800],
    'tipo_de_conta': ['corrente', 'poupanca', 'corrente', 'corrente']
}

In [4]:
df = pd.DataFrame(dados)
print(df[df['tipo_de_conta'] == 'corrente'])

   id_cliente  saldo tipo_de_conta
0         101    500      corrente
2         103   7000      corrente
3         104    800      corrente

In [5]:
df.loc[:2, 'id_cliente']

0    101
1    102
2    103
Name: id_cliente, dtype: int64

In [8]:
df.iloc[1:, 1:]

   saldo tipo_de_conta
1   6500      poupanca
2   7000      corrente
3    800      corrente

Tratamento nulo
Durante a limpeza de tratamento dos dados, é comum lidar com dados faltantes: A biblioteca Pandas oferece funcionalidades para encontrar e tratar esses valores nulos.
ISNA - Para verificar a presença de dados nulos em uma DataFrame ou Series, podemos usar o método isna(). Ele verifica cada elemento e retorna TRUE se o valor for nulo.
Valores booleanos pode ser identificados como números interiros, onde TRUE é equivalente a 1 e FALSE a 0. Podemos usar o método de agregação sum junto com isna() para contar a quantidade de valores nulos em um DataFrame.

fillna: o método fillna() substitui os valores nulos por um valor escolhido pelo usuário.

In [11]:
import numpy as np

In [12]:
dados = {
    'id_cliente': [101, 102, 103,104],
    'saldo': [np.nan, 6500, 7000, 800],
    'tipo_de_conta': ['corrente', 'poupanca', np.nan, 'corrente']
}

In [14]:
df = pd.DataFrame(dados)
df.isna()

   id_cliente  saldo  tipo_de_conta
0       False   True          False
1       False  False          False
2       False  False           True
3       False  False          False